name: Realeses

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: actions/create-release@v2
        id: create_release
        with:
          draft: false
          prerelease: false
          
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - first change
            - second change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
